### ISSUE TITLE
Alternate file

### ISSUE THREAD

**Issue by davidosomething** [zdharma/zplugin-crasis#1]
I keep my zplugin definitions in a different file
https://github.com/davidosomething/dotfiles/blob/45b80c81ba5a571b5de7d83ab1cc1781fcb6ffc4/zsh/zplugin.zsh

How can I point crasis to this?

**Comment by psprint** [comment]
Sorry for not pointing how to do it, but 2 days ago the project was in "preliminary" state, I didn't announce yet and I'm now finishing last bits. As for your question, crasis can obtain alternate Zsh file via first argument.

**Comment by psprint** [comment]
Can I ask you for any feedback on Crasis?
